<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE test [
  <!ELEMENT test (question+)>
  <!ELEMENT question (wording,choices)>
  <!ELEMENT wording (#PCDATA)>
  <!ELEMENT choices (choice+)>
  <!ELEMENT choice (#PCDATA)>
  <!ATTLIST question id CDATA #REQUIRED>
  <!ATTLIST choice correct (yes|no) "no">
]>
<test>
  <question id="1">
    <wording>¿Qué significa XML?</wording>
    <choices>
      <choice correct="yes">Extensible Markup Language</choice>
      <choice>Executable Multiple Language</choice>
      <choice>Extra Modern Link</choice>
      <choice>Examine Multiple Language</choice>
    </choices>
  </question>
  </test>